language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
script: npm run $NPM_COMMAND
sudo: false
env:
  matrix:
    - NPM_COMMAND=test
    - NPM_COMMAND=test-with-coverage
matrix:
  exclude:
    # don't collect code coverage more than once
    - node_js: "0.12"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "4"
      env: NPM_COMMAND=test-with-coverage
    # already tested with coverage
    - node_js: "5"
      env: NPM_COMMAND=test
